# This is a basic workflow to help you get started with Actions

name: Zip and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Zip-It
        uses: vimtor/action-zip@v1.2
        with:
         # Files or directories to zip
         files: ./*
         # Name of output zip file
         dest: wallpapers.zip
         # Whether to add subdirectories to simply zip all files to the root
         recursive: true

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "wallpapers.zip"
          body: |
              New Version Released! Download it Now!
          
